[project]
name = 'Tokenized-Data-Governance-Audit-Trail-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-logging]
path = 'contracts/access-logging.clar'
clarity_version = 2
epoch = 2.5

[contracts.change-tracking]
path = 'contracts/change-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
